spring:
  application:
    name: dm-user-provider
  datasource:
    url: jdbc:mysql://192.168.230.130:3306/dm_user?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.230.130
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /
  redis:
    database: 0
    host: 192.168.230.130
    port: 6379
    user: root
    password: 123456
    timeout: 3000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
moduleName: user_provider 

  profiles: provider1
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
       #defaultZone: http://root:123456@192.168.230.130:7776/eureka/
       defaultZone: http://root:123456@localhost:7776/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 7011
