server:
  port: 7900
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jonneykang/dm-sprint2.0.git
          username: xxxxxxx
          password: xxxxxxx
          search-paths: config-repo
  application:
    name: dm-config-server
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@192.168.230.130:7776/eureka/
      #defaultZone: http://root:123456@localhost:7776/eureka/
  instance:
    prefer-ip-address: true